### PR TITLE
Replace HCPCS code with RxNorm code

### PR DESCRIPTION
**Pull request by yunwwang**
This Pull Request include changes for using RxNorm codes in ImmunosuppressiveDrug topics.

### CODE REVIEW

**Comment by yuliumitre** [comment]
@yunwwang Do you have a test-ehr branch which contains the test data for this PR? Thanks.

**Comment by yunwwang** [comment]
Yes. That PR has been approved. https://github.com/HL7-DaVinci/test-ehr/pull/41/files

**Comment by yuliumitre** [comment]
Are we supposed to support both J codes and RxNorm codes?

**Comment by yunwwang** [comment]
I think only the RxNorm code

**Comment by yuliumitre** [comment]
Then we probably need to remove those J codes from the meta data. Let us confirm with Carmela. Thanks.

**Review by yuliumitre — APPROVED** [review]

**Pull request merged**
