### PR TITLE
DMEERX-792 Formalize Diagnoses

### PR DESCRIPTION
**Pull request by yuliumitre**
This PR formalizes how the relevant and other diagnoses are retrieved and displayed on order, F2F, progress note if applicable for the topics and forms current in Master branch. 

If there is a qualifying condition valueset defined, the CQL will retrieve the relevant conditions using it. 
Then retrieve other diagnoses by filtering out the relevant conditions. 

1. ImmunoSuppressive Progress Note
2. HomeOxygenTherapy
3. RAD 
4. Ventilator
5. CPAP
6. Urological Supply Progress Note
7. Hospital bed
8. HomeBlood Glucose Monitor Order and F2F

### CODE REVIEW

**Review by yunwwang — APPROVED** [review]
Looks good

**Review by hossenlopp — CHANGES_REQUESTED** [review]
Since this touches almost every ruleset, this PR should be held off until we get all other PRs for rulesets merged. These changes may need to be re-done after the other other PRs have been merged.

The HBGM Order work should NOT have been merged into this branch as it is still under PR review pending merge.

**Comment by yuliumitre** [comment]
@hossenlopp Hi Chris, the reason I merged HBGM branch to this branch is the other branch has been approved and I meant to handle any merge conflict in my branch. (My efforts tried to cover as many topics as I can in this PR :-))
I don't agree this PR should wait till all other PRs are merged. This PR covers the existing forms in master. Other PRs in review (HHS order and F2F, Urological order, HBGM lab, NEAT) contain new forms and the agreement in the team is for the new forms to follow the same guidance to implement the diagnoses. Once this PR is merged and we can still help other diagnoses in other PRs if needed. I think this is the better way for us to move forward and we can talk more if needed.

**Comment by hossenlopp** [comment]
@yuliumitre I looked at this closer. It makes more sense to me now. This PR only makes changes in the same files that the HBGM Order PR makes, the other PRs do not conflict. It still doesn't make sense to me why you merged that PR's branch into this one instead of just making changes on that one or requesting that I make changes. Merging that branch in will just create more work for you to sort out before this PR is able to be merged cleanly.

Nonetheless, this should not be merged until after the HBGM Order PR is merged. If you hadn't merged that branch in, this would be in better shape to be merged into master sooner.

**Comment by yuliumitre** [comment]
Yeah, sure. I am assuming that HBGM-order branch will be merged first :-). No, I haven't merged that branch and I am waiting for you to that whenever you think it is ready.

**Comment by hossenlopp** [comment]
Why was this merged into `hbgm-order`?

**Pull request merged**
